title: unsweets.log
subtitle: Frontend & Android
description: unsweets.logは主にAndroid開発とフロントエンドに関するウェブログです。
author: _X_y_z_
language: ja
timezone: Asia/Tokyo
url: https://blog.unsweets.net
root: /
permalink: :year/:month/:title.html
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - admin/config.yml
new_post_name: :title.md
default_layout: post
titlecase: false
external_link: false
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: null
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY/MM/DD
time_format: HH:mm:ss
per_page: 0
pagination_dir: page
theme: hanayo
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub: null
  content: null
archive_generator:
  per_page: 0
  yearly: false
  monthly: false
  daily: false
twitter: _X_y_z_
github: sunya9
disqus_shortname: unsweets-log
menu:
  - href: /about/
    name: About
  - href: /archives/
    name: Archives
marked:
  gfm: true
  sanitize: false
  tables: true
  breaks: false
  smartLists: true
  smartypants: true
html_minifier:
  enable: true
  removeComments: true
  removeAttributeQuotes: true
css_minifier:
  enable: false
js_minifier:
  enable: false
image_minifier:
  enable: false
