backend:
  name: github
  repo: sunya9/unsweets.log
publish_mode: editorial_workflow
media_folder: "content/images"

collections:
  - name: "article"
    label: "Article"
    folder: "content/blog/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Date", name: "date", widget: "datetime", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm:ss", format: "YYYY-MM-DD HH:mm:ss", default: ""}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "page"
    label: "Page"
    folder: "content/pages/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Content", name: "body", widget: "markdown"}
